name: Build App

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Setup Python (for backend)
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Install PyInstaller
              run: pip install pyinstaller

            - name: Install backend Python dependencies
              working-directory: resources/backend
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Install dependencies
              run: npm ci

            - name: Build app
              run: |
                  npm run build-backend
                  npm run build
                  if [[ "${{ runner.os }}" == "Windows" ]]; then
                    npx electron-builder --win
                  elif [[ "${{ runner.os }}" == "macOS" ]]; then
                    npx electron-builder --mac
                  else
                    npx electron-builder --linux
                  fi
              shell: bash

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: minitasks-${{ runner.os }}
                  path: |
                      dist/*.exe        
                      dist/*.dmg        
                      dist/*.AppImage   
                      dist/*.deb       
                      dist/*.snap
